# Generated by Django 5.1.2 on 2026-04-04 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clubimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Әкімшілік персонал', 'verbose_name_plural': 'Әкімшілік персонал'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Лауазымы / Пәні'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Негізгі сурет')),
                ('section', models.CharField(choices=[('psychology', 'Психология'), ('social', 'Әлеуметтік жұмыс'), ('medical', 'Медициналық қызмет'), ('guardian', 'Қамқоршылық кеңес')], max_length=20, verbose_name='Бөлім')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарияланған')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мақала',
                'verbose_name_plural': 'Мақалалар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/gallery/', verbose_name='Сурет')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Сипаттама')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.article', verbose_name='Мақала')),
            ],
            options={
                'verbose_name': 'Қосымша сурет',
                'verbose_name_plural': 'Қосымша суреттер',
            },
        ),
    ]
