# Generated by Django 5.1.2 on 2026-04-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_teacher_options_alter_teacher_subject_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Қамқоршылық кеңес мақаласы',
                'verbose_name_plural': 'Қамқоршылық кеңес',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.article',),
        ),
        migrations.CreateModel(
            name='MedicalArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Медициналық қызмет мақаласы',
                'verbose_name_plural': 'Медициналық қызмет',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.article',),
        ),
        migrations.CreateModel(
            name='PsychologyArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Психология мақаласы',
                'verbose_name_plural': 'Психология мақалалары',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.article',),
        ),
        migrations.CreateModel(
            name='SocialArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Әлеуметтік жұмыс мақаласы',
                'verbose_name_plural': 'Әлеуметтік жұмыс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.article',),
        ),
    ]
