# Generated by Django 5.1.2 on 2026-04-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_guardianarticle_medicalarticle_psychologyarticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Тек өзіңізге түсінікті болу үшін', max_length=200, verbose_name='Атауы немесе сипаттамасы')),
                ('embed_code', models.TextField(help_text='Инстаграмнан алынған HTML кодты осында қойыңыз', verbose_name='Instagram Embed коды')),
                ('is_active', models.BooleanField(default=True, verbose_name='Көрсету')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Инстаграм рилс',
                'verbose_name_plural': 'Инстаграм рилстары',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
            ],
            options={
                'verbose_name': 'Кітап санаты',
                'verbose_name_plural': 'Кітап санаттары',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сипаттамасы'),
        ),
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.URLField(blank=True, help_text='Сыртқы сілтеме — файл жүктемей, тікелей URL беру үшін', verbose_name='Сілтеме (URL)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Word, PDF, Excel және т.б. файлдарды жүктеңіз', null=True, upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Кітап атауы')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='library/', verbose_name='Мұқаба суреті')),
                ('file', models.FileField(blank=True, help_text='Электронды кітапты жүктеңіз', null=True, upload_to='library/files/', verbose_name='Файл (PDF, Word)')),
                ('link', models.URLField(blank=True, help_text='Google Drive, т.б. сілтеме', verbose_name='Сыртқы сілтеме')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарияланған')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='app.librarycategory', verbose_name='Санаты')),
            ],
            options={
                'verbose_name': 'Кітап',
                'verbose_name_plural': 'Кітапхана',
                'ordering': ['category__order', 'title'],
            },
        ),
    ]
