# Generated by Django 5.1.2 on 2026-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_instagramreel_librarycategory_document_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='book_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ (Номер)'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тақырыбы / Тема'),
        ),
    ]
