# Generated by Django 5.1.2 on 2026-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_librarybook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='Лауазымы / Пәні'),
        ),
    ]
