# Generated by Django 5.1.2 on 2026-04-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Санат атауы (мысалы: Жетістіктер, Жетекшілер)')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
            ],
            options={
                'verbose_name': 'Әдістемелік санат',
                'verbose_name_plural': '1. Әдістемелік санаттар',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MethodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аты / Тақырыбы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image', models.ImageField(blank=True, null=True, upload_to='methodo/images/', verbose_name='Сурет')),
                ('file', models.FileField(blank=True, help_text='Word, PPTX, RAR немесе кез-келген құжат', null=True, upload_to='methodo/files/', verbose_name='Документ (PPTX, Word, RAR)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.methodocategory', verbose_name='Бірлестік санаты')),
            ],
            options={
                'verbose_name': 'Материал немесе Жетістік',
                'verbose_name_plural': '2. Материалдар мен Жетістіктер',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
