# Generated by Django 5.1.2 on 2026-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_methodocategory_methodoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodoitem',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='methodo/images/', verbose_name='2-ші Сурет (фото)'),
        ),
        migrations.AlterField(
            model_name='methodoitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='methodo/images/', verbose_name='1-ші Сурет (фото)'),
        ),
    ]
