# Generated by Django 5.1.2 on 2026-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_methodoitem_image2_alter_methodoitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhetistikItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='zhetistik/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='zhetistik/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, help_text='PDF, Word, PPTX немесе кез-келген құжат', null=True, upload_to='zhetistik/files/', verbose_name='Документ (PDF, Word, PPTX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Жетістік',
                'verbose_name_plural': 'Жетістіктер',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagistrItem',
            fields=[
            ],
            options={
                'verbose_name': 'Педагогика ғылымдарының магистрі',
                'verbose_name_plural': 'Педагогика ғылымдарының магистрі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.methodoitem',),
        ),
        migrations.CreateModel(
            name='SanatItem',
            fields=[
            ],
            options={
                'verbose_name': 'Біліктілік санат',
                'verbose_name_plural': 'Біліктілік санат',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.methodoitem',),
        ),
        migrations.CreateModel(
            name='ZhetekshilerItem',
            fields=[
            ],
            options={
                'verbose_name': 'Өдістемелік бірлестік жетекшілері',
                'verbose_name_plural': 'Өдістемелік бірлестік жетекшілері',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.methodoitem',),
        ),
    ]
