# Generated by Django 5.1.2 on 2026-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_zhetistikitem_magistritem_sanatitem_zhetekshileritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BastauyshItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Taqyryby')),
                ('description', models.TextField(blank=True, verbose_name='Sipattama')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='bastauysh/', verbose_name='1-shi Foto')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='bastauysh/', verbose_name='2-shi Foto')),
                ('file', models.FileField(blank=True, null=True, upload_to='bastauysh/files/', verbose_name='Fayl (PDF, Word, PPTX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rettіlіk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qosylghan uaqyty')),
            ],
            options={
                'verbose_name': 'Bastauysh synyp',
                'verbose_name_plural': 'Bastauysh synyp',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarbieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Taqyryby')),
                ('description', models.TextField(blank=True, verbose_name='Sipattama')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='tarbie_oryn/', verbose_name='1-shi Foto')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='tarbie_oryn/', verbose_name='2-shi Foto')),
                ('file', models.FileField(blank=True, null=True, upload_to='tarbie_oryn/files/', verbose_name='Fayl (PDF, Word, PPTX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rettіlіk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qosylghan uaqyty')),
            ],
            options={
                'verbose_name': 'Tarbie orynbasary',
                'verbose_name_plural': 'Tarbie orynbasary',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Taqyryby')),
                ('description', models.TextField(blank=True, verbose_name='Sipattama')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='timetable/', verbose_name='1-shi Foto/Keste')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='timetable/', verbose_name='2-shi Foto/Keste')),
                ('file', models.FileField(blank=True, null=True, upload_to='timetable/files/', verbose_name='Fayl (PDF, Word)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rettіlіk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qosylghan uaqyty')),
            ],
            options={
                'verbose_name': 'Sabaq kestesi',
                'verbose_name_plural': '5-11 Synyp sabaq kestesi',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
