# Generated by Django 5.1.2 on 2026-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bastauyshitem_tarbieitem_timetableitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsMeetingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Taqyryby')),
                ('description', models.TextField(blank=True, verbose_name='Sipattama')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='parents_meeting/', verbose_name='1-shi Foto')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='parents_meeting/', verbose_name='2-shi Foto')),
                ('file', models.FileField(blank=True, null=True, upload_to='parents_meeting/files/', verbose_name='Fayl (PDF, Word, PPTX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Rettіlіk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ata-analar zhinalysy',
                'verbose_name_plural': 'Ata-analar zhinalysy',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
