# Generated by Django 5.1.2 on 2026-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_parentsmeetingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarbieitem',
            name='link',
            field=models.URLField(blank=True, help_text='Google Drive siltemesin osy jerge qoyyңyz. Mysal: https://drive.google.com/...', verbose_name='Google Drive / Silteme (URL)'),
        ),
    ]
