# Generated by Django 5.1.2 on 2026-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tarbieitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Егер суреттің орнына Инстаграм видео қойғыңыз келсе, осында сілтемені жазыңыз', null=True, verbose_name='Instagram видео сілтемесі'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/', verbose_name='Сурет'),
        ),
    ]
