# Generated by Django 5.1.2 on 2026-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_galleryimage_instagram_link_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdalUrpaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='adal_urpaq/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='adal_urpaq/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='adal_urpaq/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Адал ұрпақ',
                'verbose_name_plural': 'Адал ұрпақ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AskhanaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='askhana/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='askhana/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, help_text='PDF, Word, PPTX немесе кез-келген құжат', null=True, upload_to='askhana/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, help_text='Google Drive немесе басқа сілтеме URL', verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Асхана',
                'verbose_name_plural': 'Асхана',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IshkiTartip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ishki_tartip/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ishki_tartip/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='ishki_tartip/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Мектептің ішкі тәртіп ережелері',
                'verbose_name_plural': 'Мектептің ішкі тәртіп ережелері',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IsShara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Іс-шара аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='is_shara/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='is_shara/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, help_text='PDF, Word, PPTX немесе кез-келген құжат', null=True, upload_to='is_shara/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, help_text='Google Drive немесе басқа сілтеме URL', verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Іс-шара',
                'verbose_name_plural': 'Іс-шаралар',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parlament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='parlament/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='parlament/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='parlament/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Мектеп парламенті',
                'verbose_name_plural': 'Мектеп парламенті',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedQoldau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ped_qoldau/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ped_qoldau/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='ped_qoldau/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Педагогикалық қолдау орталығы',
                'verbose_name_plural': 'Педагогикалық қолдау орталығы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profilaktika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='profilaktika/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='profilaktika/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='profilaktika/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Құқықбұзушылықтың алдын алу',
                'verbose_name_plural': 'Құқықбұзушылықтың алдын алу',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZhasUlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='zhas_ulan/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='zhas_ulan/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='zhas_ulan/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Жас ұлан',
                'verbose_name_plural': 'Жас ұлан',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZhylJospar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы / Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='zhyl_jospar/', verbose_name='1-ші Фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='zhyl_jospar/', verbose_name='2-ші Фото')),
                ('file', models.FileField(blank=True, help_text='PDF, Word, PPTX немесе кез-келген құжат', null=True, upload_to='zhyl_jospar/files/', verbose_name='Файл (PDF, Word, PPTX)')),
                ('link', models.URLField(blank=True, help_text='Google Drive немесе басқа сілтеме URL', verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Жылдық жоспар',
                'verbose_name_plural': 'Жылдық жоспар',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
