# Generated by Django 5.1.2 on 2026-10-01 13:16

import django.db.models.deletion
from django.db import migrations, models


def create_attestation_years(apps, schema_editor):
    AttestationYear = apps.get_model('app', 'AttestationYear')
    years = [
        ('2024-2025', 1),
        ('2025-2026', 2),
        ('2026-2027', 3),
    ]
    for title, order in years:
        AttestationYear.objects.get_or_create(
            slug=title, defaults={'title': title, 'order': order}
        )


def remove_attestation_years(apps, schema_editor):
    AttestationYear = apps.get_model('app', 'AttestationYear')
    AttestationYear.objects.filter(
        slug__in=['2024-2025', '2025-2026', '2026-2027']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_adalurpaq_askhanaitem_ishkitartip_isshara_parlament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Мысалы: 2024-2025', max_length=50, verbose_name='Оқу жылы')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('is_active', models.BooleanField(default=True, verbose_name='Көрсету')),
            ],
            options={
                'verbose_name': 'Аттестация оқу жылы',
                'verbose_name_plural': 'Аттестация оқу жылдары',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AttestationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('file', models.FileField(blank=True, help_text='PDF, Word, Excel, PPTX немесе басқа файлды жүктеңіз', null=True, upload_to='attestation/', verbose_name='Файл')),
                ('link', models.URLField(blank=True, help_text='Файл жүктемей, сыртқы сілтеме беру үшін', verbose_name='Сілтеме (Google Drive т.б.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.attestationyear', verbose_name='Оқу жылы')),
            ],
            options={
                'verbose_name': 'Аттестация құжаты',
                'verbose_name_plural': 'Аттестация құжаттары',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RunPython(create_attestation_years, remove_attestation_years),
    ]
