# Generated by Django 5.1.2 on 2026-10-03 10:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_attestationnode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationnode',
            name='file',
            field=models.FileField(blank=True, help_text='Тек PDF форматы, өлшемі 50 МБ-тан аспайды.', null=True, upload_to=app.models.attestation_upload_to, validators=[app.models.validate_pdf_file], verbose_name='Файл (PDF)'),
        ),
    ]
