# Generated by Django 5.1.2 on 2026-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_attestationnode_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcategory',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Стандартная таблица'), (2, 'Таблица по годам'), (3, 'Таблица с вложенными годами в ячейке'), (4, 'Многоуровневая таблица'), (5, 'Стандартная таблица (раскрывающаяся)')], default=1, help_text='Сайттағы кесте түрін анықтайды', verbose_name='Блок түрі'),
        ),
    ]
