# Generated by Django 5.1.2 on 2026-10-04 05:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_attestation_collapsible_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhetekshilerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('file', models.FileField(blank=True, help_text='Тек PDF форматы, өлшемі 50 МБ-тан аспайды.', null=True, upload_to=app.models.zhetekshiler_upload_to, validators=[app.models.validate_pdf_file], verbose_name='PDF файлы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Жетекшілер құжаты (PDF)',
                'verbose_name_plural': 'Жетекшілер құжаттары (PDF)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
