# Generated by Django 5.1.2 on 2026-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_zhetekshilerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Тек PDF форматындағы файлды жүктеуге болады. Өлшемі 50 МБ-тан аспауы керек.', null=True, upload_to='documents/', verbose_name='Файл'),
        ),
    ]
